### ISSUE TITLE
Do not update pinned versions

### ISSUE THREAD

**Issue by MrP01** [MousaZeidBaker/poetryup#33]
Hello!
Thank you so much for the package. I think it would be great to add an option `--no-pinned` or similar, which prevents poetryup from updating packages pinned to a specific exact version using "=".

```toml
[tool.poetry.dependencies]
packagetoupdate = "^5.2.1"
pinnedpackage = "1.2.3"
```

After running `poetryup --latest --no-pinned`, the result should look like this:

```toml
[tool.poetry.dependencies]
packagetoupdate = "^6.0.0"
pinnedpackage = "1.2.3"
```

The idea is that some packages introduce too drastic changes with the next version, which should be exempt from the updating process. Maybe manual review (such as `yarn upgrade-interactive`) is an option here too, but I guess this is a different topic.
